// flow-typed signature: 3a791c43f5d248192569413813d6e4bd
// flow-typed version: <<STUB>>/copy-to-clipboard_v^3.0.5/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'copy-to-clipboard'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'copy-to-clipboard' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'copy-to-clipboard/example/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'copy-to-clipboard/example/index.js' {
  declare module.exports: $Exports<'copy-to-clipboard/example/index'>;
}
declare module 'copy-to-clipboard/index' {
  declare module.exports: $Exports<'copy-to-clipboard'>;
}
declare module 'copy-to-clipboard/index.js' {
  declare module.exports: $Exports<'copy-to-clipboard'>;
}
