// flow-typed signature: 1da3d500b3dfc90be037e4576f05d934
// flow-typed version: <<STUB>>/exhibit-plugin-browserify_v^0.12.0/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'exhibit-plugin-browserify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'exhibit-plugin-browserify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'exhibit-plugin-browserify/getCreateDeps' {
  declare module.exports: any;
}

// Filename aliases
declare module 'exhibit-plugin-browserify/getCreateDeps.js' {
  declare module.exports: $Exports<'exhibit-plugin-browserify/getCreateDeps'>;
}
declare module 'exhibit-plugin-browserify/index' {
  declare module.exports: $Exports<'exhibit-plugin-browserify'>;
}
declare module 'exhibit-plugin-browserify/index.js' {
  declare module.exports: $Exports<'exhibit-plugin-browserify'>;
}
