// flow-typed signature: 0462464b42056083192d3f3b87ca1705
// flow-typed version: <<STUB>>/exhibit-plugin-autoprefixer_v^0.12.0/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'exhibit-plugin-autoprefixer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'exhibit-plugin-autoprefixer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'exhibit-plugin-autoprefixer/index' {
  declare module.exports: $Exports<'exhibit-plugin-autoprefixer'>;
}
declare module 'exhibit-plugin-autoprefixer/index.js' {
  declare module.exports: $Exports<'exhibit-plugin-autoprefixer'>;
}
