// flow-typed signature: 757dabb1ef560f8698298a18a5f9dddd
// flow-typed version: <<STUB>>/exhibit-plugin-babel_v^0.13.1/flow_v0.57.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'exhibit-plugin-babel'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'exhibit-plugin-babel' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'exhibit-plugin-babel/index' {
  declare module.exports: $Exports<'exhibit-plugin-babel'>;
}
declare module 'exhibit-plugin-babel/index.js' {
  declare module.exports: $Exports<'exhibit-plugin-babel'>;
}
