// flow-typed signature: dd2890c544fb653fbe79cfdfe84bd455
// flow-typed version: <<STUB>>/exhibit-plugin-uglify_v^0.12.0/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'exhibit-plugin-uglify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'exhibit-plugin-uglify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'exhibit-plugin-uglify/index' {
  declare module.exports: $Exports<'exhibit-plugin-uglify'>;
}
declare module 'exhibit-plugin-uglify/index.js' {
  declare module.exports: $Exports<'exhibit-plugin-uglify'>;
}
