// flow-typed signature: 6d2fead6ccf173d92011afc656096cc5
// flow-typed version: <<STUB>>/ft-graphics-deploy_v^2.1.4/flow_v0.135.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ft-graphics-deploy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ft-graphics-deploy' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ft-graphics-deploy/cli' {
  declare module.exports: any;
}

declare module 'ft-graphics-deploy/dist/cli' {
  declare module.exports: any;
}

declare module 'ft-graphics-deploy/dist/cli.test' {
  declare module.exports: any;
}

declare module 'ft-graphics-deploy/dist/Deployer' {
  declare module.exports: any;
}

declare module 'ft-graphics-deploy/dist/help' {
  declare module.exports: any;
}

declare module 'ft-graphics-deploy/dist' {
  declare module.exports: any;
}

declare module 'ft-graphics-deploy/dist/vault' {
  declare module.exports: any;
}

declare module 'ft-graphics-deploy/dist/verifyGit' {
  declare module.exports: any;
}

declare module 'ft-graphics-deploy/setup' {
  declare module.exports: any;
}

declare module 'ft-graphics-deploy/src/cli' {
  declare module.exports: any;
}

declare module 'ft-graphics-deploy/src/cli.test' {
  declare module.exports: any;
}

declare module 'ft-graphics-deploy/src/Deployer' {
  declare module.exports: any;
}

declare module 'ft-graphics-deploy/src/help' {
  declare module.exports: any;
}

declare module 'ft-graphics-deploy/src' {
  declare module.exports: any;
}

declare module 'ft-graphics-deploy/src/vault' {
  declare module.exports: any;
}

declare module 'ft-graphics-deploy/src/verifyGit' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ft-graphics-deploy/cli.js' {
  declare module.exports: $Exports<'ft-graphics-deploy/cli'>;
}
declare module 'ft-graphics-deploy/dist/cli.js' {
  declare module.exports: $Exports<'ft-graphics-deploy/dist/cli'>;
}
declare module 'ft-graphics-deploy/dist/cli.test.js' {
  declare module.exports: $Exports<'ft-graphics-deploy/dist/cli.test'>;
}
declare module 'ft-graphics-deploy/dist/Deployer.js' {
  declare module.exports: $Exports<'ft-graphics-deploy/dist/Deployer'>;
}
declare module 'ft-graphics-deploy/dist/help.js' {
  declare module.exports: $Exports<'ft-graphics-deploy/dist/help'>;
}
declare module 'ft-graphics-deploy/dist/index' {
  declare module.exports: $Exports<'ft-graphics-deploy/dist'>;
}
declare module 'ft-graphics-deploy/dist/index.js' {
  declare module.exports: $Exports<'ft-graphics-deploy/dist'>;
}
declare module 'ft-graphics-deploy/dist/vault.js' {
  declare module.exports: $Exports<'ft-graphics-deploy/dist/vault'>;
}
declare module 'ft-graphics-deploy/dist/verifyGit.js' {
  declare module.exports: $Exports<'ft-graphics-deploy/dist/verifyGit'>;
}
declare module 'ft-graphics-deploy/setup.js' {
  declare module.exports: $Exports<'ft-graphics-deploy/setup'>;
}
declare module 'ft-graphics-deploy/src/cli.js' {
  declare module.exports: $Exports<'ft-graphics-deploy/src/cli'>;
}
declare module 'ft-graphics-deploy/src/cli.test.js' {
  declare module.exports: $Exports<'ft-graphics-deploy/src/cli.test'>;
}
declare module 'ft-graphics-deploy/src/Deployer.js' {
  declare module.exports: $Exports<'ft-graphics-deploy/src/Deployer'>;
}
declare module 'ft-graphics-deploy/src/help.js' {
  declare module.exports: $Exports<'ft-graphics-deploy/src/help'>;
}
declare module 'ft-graphics-deploy/src/index' {
  declare module.exports: $Exports<'ft-graphics-deploy/src'>;
}
declare module 'ft-graphics-deploy/src/index.js' {
  declare module.exports: $Exports<'ft-graphics-deploy/src'>;
}
declare module 'ft-graphics-deploy/src/vault.js' {
  declare module.exports: $Exports<'ft-graphics-deploy/src/vault'>;
}
declare module 'ft-graphics-deploy/src/verifyGit.js' {
  declare module.exports: $Exports<'ft-graphics-deploy/src/verifyGit'>;
}
