// flow-typed signature: dc5bd900907d6e3abce18a5957971b74
// flow-typed version: <<STUB>>/react-with-styles_v^1.3.0/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-with-styles'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-with-styles' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-with-styles/lib/ThemedStyleSheet' {
  declare module.exports: any;
}

declare module 'react-with-styles/lib/ThemeProvider' {
  declare module.exports: any;
}

declare module 'react-with-styles/lib/withStyles' {
  declare module.exports: any;
}

declare module 'react-with-styles/src/ThemedStyleSheet' {
  declare module.exports: any;
}

declare module 'react-with-styles/src/ThemeProvider' {
  declare module.exports: any;
}

declare module 'react-with-styles/src/withStyles' {
  declare module.exports: any;
}

declare module 'react-with-styles/test/ThemeProvider_test' {
  declare module.exports: any;
}

declare module 'react-with-styles/test/withStyles_test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-with-styles/lib/ThemedStyleSheet.js' {
  declare module.exports: $Exports<'react-with-styles/lib/ThemedStyleSheet'>;
}
declare module 'react-with-styles/lib/ThemeProvider.js' {
  declare module.exports: $Exports<'react-with-styles/lib/ThemeProvider'>;
}
declare module 'react-with-styles/lib/withStyles.js' {
  declare module.exports: $Exports<'react-with-styles/lib/withStyles'>;
}
declare module 'react-with-styles/src/ThemedStyleSheet.js' {
  declare module.exports: $Exports<'react-with-styles/src/ThemedStyleSheet'>;
}
declare module 'react-with-styles/src/ThemeProvider.jsx' {
  declare module.exports: $Exports<'react-with-styles/src/ThemeProvider'>;
}
declare module 'react-with-styles/src/withStyles.jsx' {
  declare module.exports: $Exports<'react-with-styles/src/withStyles'>;
}
declare module 'react-with-styles/test/ThemeProvider_test.jsx' {
  declare module.exports: $Exports<'react-with-styles/test/ThemeProvider_test'>;
}
declare module 'react-with-styles/test/withStyles_test.jsx' {
  declare module.exports: $Exports<'react-with-styles/test/withStyles_test'>;
}
