// flow-typed signature: abc3639c9fd365ddb9b5f60a80704ca6
// flow-typed version: <<STUB>>/react-with-styles-interface-aphrodite_v^1.2.0/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-with-styles-interface-aphrodite'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-with-styles-interface-aphrodite' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-with-styles-interface-aphrodite/lib/aphroditeInterface' {
  declare module.exports: any;
}

declare module 'react-with-styles-interface-aphrodite/lib/aphroditeInterfaceFactory' {
  declare module.exports: any;
}

declare module 'react-with-styles-interface-aphrodite/lib/no-important' {
  declare module.exports: any;
}

declare module 'react-with-styles-interface-aphrodite/no-important' {
  declare module.exports: any;
}

declare module 'react-with-styles-interface-aphrodite/src/aphroditeInterface' {
  declare module.exports: any;
}

declare module 'react-with-styles-interface-aphrodite/src/aphroditeInterfaceFactory' {
  declare module.exports: any;
}

declare module 'react-with-styles-interface-aphrodite/src/no-important' {
  declare module.exports: any;
}

declare module 'react-with-styles-interface-aphrodite/test/aphroditeInterface_test' {
  declare module.exports: any;
}

declare module 'react-with-styles-interface-aphrodite/test/aphroditeInterfaceFactory_test' {
  declare module.exports: any;
}

declare module 'react-with-styles-interface-aphrodite/test/no-imporant_test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-with-styles-interface-aphrodite/lib/aphroditeInterface.js' {
  declare module.exports: $Exports<'react-with-styles-interface-aphrodite/lib/aphroditeInterface'>;
}
declare module 'react-with-styles-interface-aphrodite/lib/aphroditeInterfaceFactory.js' {
  declare module.exports: $Exports<'react-with-styles-interface-aphrodite/lib/aphroditeInterfaceFactory'>;
}
declare module 'react-with-styles-interface-aphrodite/lib/no-important.js' {
  declare module.exports: $Exports<'react-with-styles-interface-aphrodite/lib/no-important'>;
}
declare module 'react-with-styles-interface-aphrodite/no-important.js' {
  declare module.exports: $Exports<'react-with-styles-interface-aphrodite/no-important'>;
}
declare module 'react-with-styles-interface-aphrodite/src/aphroditeInterface.js' {
  declare module.exports: $Exports<'react-with-styles-interface-aphrodite/src/aphroditeInterface'>;
}
declare module 'react-with-styles-interface-aphrodite/src/aphroditeInterfaceFactory.js' {
  declare module.exports: $Exports<'react-with-styles-interface-aphrodite/src/aphroditeInterfaceFactory'>;
}
declare module 'react-with-styles-interface-aphrodite/src/no-important.js' {
  declare module.exports: $Exports<'react-with-styles-interface-aphrodite/src/no-important'>;
}
declare module 'react-with-styles-interface-aphrodite/test/aphroditeInterface_test.js' {
  declare module.exports: $Exports<'react-with-styles-interface-aphrodite/test/aphroditeInterface_test'>;
}
declare module 'react-with-styles-interface-aphrodite/test/aphroditeInterfaceFactory_test.js' {
  declare module.exports: $Exports<'react-with-styles-interface-aphrodite/test/aphroditeInterfaceFactory_test'>;
}
declare module 'react-with-styles-interface-aphrodite/test/no-imporant_test.js' {
  declare module.exports: $Exports<'react-with-styles-interface-aphrodite/test/no-imporant_test'>;
}
