// flow-typed signature: d063f4265d5a2262d415e0f32d3a2c21
// flow-typed version: <<STUB>>/react-with-styles_v^2.2.0/flow_v0.57.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-with-styles'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-with-styles' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-with-styles/lib/ThemedStyleSheet' {
  declare module.exports: any;
}

declare module 'react-with-styles/lib/withStyles' {
  declare module.exports: any;
}

declare module 'react-with-styles/src/ThemedStyleSheet' {
  declare module.exports: any;
}

declare module 'react-with-styles/src/withStyles' {
  declare module.exports: any;
}

declare module 'react-with-styles/test/_setup' {
  declare module.exports: any;
}

declare module 'react-with-styles/test/withStyles_test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-with-styles/lib/ThemedStyleSheet.js' {
  declare module.exports: $Exports<'react-with-styles/lib/ThemedStyleSheet'>;
}
declare module 'react-with-styles/lib/withStyles.js' {
  declare module.exports: $Exports<'react-with-styles/lib/withStyles'>;
}
declare module 'react-with-styles/src/ThemedStyleSheet.js' {
  declare module.exports: $Exports<'react-with-styles/src/ThemedStyleSheet'>;
}
declare module 'react-with-styles/src/withStyles.jsx' {
  declare module.exports: $Exports<'react-with-styles/src/withStyles'>;
}
declare module 'react-with-styles/test/_setup.js' {
  declare module.exports: $Exports<'react-with-styles/test/_setup'>;
}
declare module 'react-with-styles/test/withStyles_test.jsx' {
  declare module.exports: $Exports<'react-with-styles/test/withStyles_test'>;
}
