// flow-typed signature: 19b897d5f4c6418f66b0f2511ee48c07
// flow-typed version: <<STUB>>/react-with-styles-interface-aphrodite_v^3.1.1/flow_v0.57.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-with-styles-interface-aphrodite'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-with-styles-interface-aphrodite' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-with-styles-interface-aphrodite/lib/aphroditeInterface' {
  declare module.exports: any;
}

declare module 'react-with-styles-interface-aphrodite/lib/aphroditeInterfaceFactory' {
  declare module.exports: any;
}

declare module 'react-with-styles-interface-aphrodite/lib/aphroditeInterfaceWithRTLFactory' {
  declare module.exports: any;
}

declare module 'react-with-styles-interface-aphrodite/lib/no-important' {
  declare module.exports: any;
}

declare module 'react-with-styles-interface-aphrodite/lib/utils/generateDirectionalStyles' {
  declare module.exports: any;
}

declare module 'react-with-styles-interface-aphrodite/lib/utils/resolve' {
  declare module.exports: any;
}

declare module 'react-with-styles-interface-aphrodite/lib/utils/resolveWithRTL' {
  declare module.exports: any;
}

declare module 'react-with-styles-interface-aphrodite/lib/utils/separateStyles' {
  declare module.exports: any;
}

declare module 'react-with-styles-interface-aphrodite/lib/utils/withRTLExtension' {
  declare module.exports: any;
}

declare module 'react-with-styles-interface-aphrodite/lib/with-rtl' {
  declare module.exports: any;
}

declare module 'react-with-styles-interface-aphrodite/no-important' {
  declare module.exports: any;
}

declare module 'react-with-styles-interface-aphrodite/src/aphroditeInterface' {
  declare module.exports: any;
}

declare module 'react-with-styles-interface-aphrodite/src/aphroditeInterfaceFactory' {
  declare module.exports: any;
}

declare module 'react-with-styles-interface-aphrodite/src/aphroditeInterfaceWithRTLFactory' {
  declare module.exports: any;
}

declare module 'react-with-styles-interface-aphrodite/src/no-important' {
  declare module.exports: any;
}

declare module 'react-with-styles-interface-aphrodite/src/utils/generateDirectionalStyles' {
  declare module.exports: any;
}

declare module 'react-with-styles-interface-aphrodite/src/utils/resolve' {
  declare module.exports: any;
}

declare module 'react-with-styles-interface-aphrodite/src/utils/resolveWithRTL' {
  declare module.exports: any;
}

declare module 'react-with-styles-interface-aphrodite/src/utils/separateStyles' {
  declare module.exports: any;
}

declare module 'react-with-styles-interface-aphrodite/src/utils/withRTLExtension' {
  declare module.exports: any;
}

declare module 'react-with-styles-interface-aphrodite/src/with-rtl' {
  declare module.exports: any;
}

declare module 'react-with-styles-interface-aphrodite/test/aphroditeInterface_test' {
  declare module.exports: any;
}

declare module 'react-with-styles-interface-aphrodite/test/aphroditeInterfaceFactory_test' {
  declare module.exports: any;
}

declare module 'react-with-styles-interface-aphrodite/test/aphroditeInterfaceWithRTLFactory_test' {
  declare module.exports: any;
}

declare module 'react-with-styles-interface-aphrodite/test/no-important_test' {
  declare module.exports: any;
}

declare module 'react-with-styles-interface-aphrodite/test/utils/generateDirectionalStyles_test' {
  declare module.exports: any;
}

declare module 'react-with-styles-interface-aphrodite/test/utils/resolve_test' {
  declare module.exports: any;
}

declare module 'react-with-styles-interface-aphrodite/test/utils/resolveWithRTL_test' {
  declare module.exports: any;
}

declare module 'react-with-styles-interface-aphrodite/test/utils/withRTLExtension_test' {
  declare module.exports: any;
}

declare module 'react-with-styles-interface-aphrodite/test/with-rtl_test' {
  declare module.exports: any;
}

declare module 'react-with-styles-interface-aphrodite/with-rtl' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-with-styles-interface-aphrodite/lib/aphroditeInterface.js' {
  declare module.exports: $Exports<'react-with-styles-interface-aphrodite/lib/aphroditeInterface'>;
}
declare module 'react-with-styles-interface-aphrodite/lib/aphroditeInterfaceFactory.js' {
  declare module.exports: $Exports<'react-with-styles-interface-aphrodite/lib/aphroditeInterfaceFactory'>;
}
declare module 'react-with-styles-interface-aphrodite/lib/aphroditeInterfaceWithRTLFactory.js' {
  declare module.exports: $Exports<'react-with-styles-interface-aphrodite/lib/aphroditeInterfaceWithRTLFactory'>;
}
declare module 'react-with-styles-interface-aphrodite/lib/no-important.js' {
  declare module.exports: $Exports<'react-with-styles-interface-aphrodite/lib/no-important'>;
}
declare module 'react-with-styles-interface-aphrodite/lib/utils/generateDirectionalStyles.js' {
  declare module.exports: $Exports<'react-with-styles-interface-aphrodite/lib/utils/generateDirectionalStyles'>;
}
declare module 'react-with-styles-interface-aphrodite/lib/utils/resolve.js' {
  declare module.exports: $Exports<'react-with-styles-interface-aphrodite/lib/utils/resolve'>;
}
declare module 'react-with-styles-interface-aphrodite/lib/utils/resolveWithRTL.js' {
  declare module.exports: $Exports<'react-with-styles-interface-aphrodite/lib/utils/resolveWithRTL'>;
}
declare module 'react-with-styles-interface-aphrodite/lib/utils/separateStyles.js' {
  declare module.exports: $Exports<'react-with-styles-interface-aphrodite/lib/utils/separateStyles'>;
}
declare module 'react-with-styles-interface-aphrodite/lib/utils/withRTLExtension.js' {
  declare module.exports: $Exports<'react-with-styles-interface-aphrodite/lib/utils/withRTLExtension'>;
}
declare module 'react-with-styles-interface-aphrodite/lib/with-rtl.js' {
  declare module.exports: $Exports<'react-with-styles-interface-aphrodite/lib/with-rtl'>;
}
declare module 'react-with-styles-interface-aphrodite/no-important.js' {
  declare module.exports: $Exports<'react-with-styles-interface-aphrodite/no-important'>;
}
declare module 'react-with-styles-interface-aphrodite/src/aphroditeInterface.js' {
  declare module.exports: $Exports<'react-with-styles-interface-aphrodite/src/aphroditeInterface'>;
}
declare module 'react-with-styles-interface-aphrodite/src/aphroditeInterfaceFactory.js' {
  declare module.exports: $Exports<'react-with-styles-interface-aphrodite/src/aphroditeInterfaceFactory'>;
}
declare module 'react-with-styles-interface-aphrodite/src/aphroditeInterfaceWithRTLFactory.js' {
  declare module.exports: $Exports<'react-with-styles-interface-aphrodite/src/aphroditeInterfaceWithRTLFactory'>;
}
declare module 'react-with-styles-interface-aphrodite/src/no-important.js' {
  declare module.exports: $Exports<'react-with-styles-interface-aphrodite/src/no-important'>;
}
declare module 'react-with-styles-interface-aphrodite/src/utils/generateDirectionalStyles.js' {
  declare module.exports: $Exports<'react-with-styles-interface-aphrodite/src/utils/generateDirectionalStyles'>;
}
declare module 'react-with-styles-interface-aphrodite/src/utils/resolve.js' {
  declare module.exports: $Exports<'react-with-styles-interface-aphrodite/src/utils/resolve'>;
}
declare module 'react-with-styles-interface-aphrodite/src/utils/resolveWithRTL.js' {
  declare module.exports: $Exports<'react-with-styles-interface-aphrodite/src/utils/resolveWithRTL'>;
}
declare module 'react-with-styles-interface-aphrodite/src/utils/separateStyles.js' {
  declare module.exports: $Exports<'react-with-styles-interface-aphrodite/src/utils/separateStyles'>;
}
declare module 'react-with-styles-interface-aphrodite/src/utils/withRTLExtension.js' {
  declare module.exports: $Exports<'react-with-styles-interface-aphrodite/src/utils/withRTLExtension'>;
}
declare module 'react-with-styles-interface-aphrodite/src/with-rtl.js' {
  declare module.exports: $Exports<'react-with-styles-interface-aphrodite/src/with-rtl'>;
}
declare module 'react-with-styles-interface-aphrodite/test/aphroditeInterface_test.js' {
  declare module.exports: $Exports<'react-with-styles-interface-aphrodite/test/aphroditeInterface_test'>;
}
declare module 'react-with-styles-interface-aphrodite/test/aphroditeInterfaceFactory_test.js' {
  declare module.exports: $Exports<'react-with-styles-interface-aphrodite/test/aphroditeInterfaceFactory_test'>;
}
declare module 'react-with-styles-interface-aphrodite/test/aphroditeInterfaceWithRTLFactory_test.js' {
  declare module.exports: $Exports<'react-with-styles-interface-aphrodite/test/aphroditeInterfaceWithRTLFactory_test'>;
}
declare module 'react-with-styles-interface-aphrodite/test/no-important_test.js' {
  declare module.exports: $Exports<'react-with-styles-interface-aphrodite/test/no-important_test'>;
}
declare module 'react-with-styles-interface-aphrodite/test/utils/generateDirectionalStyles_test.js' {
  declare module.exports: $Exports<'react-with-styles-interface-aphrodite/test/utils/generateDirectionalStyles_test'>;
}
declare module 'react-with-styles-interface-aphrodite/test/utils/resolve_test.js' {
  declare module.exports: $Exports<'react-with-styles-interface-aphrodite/test/utils/resolve_test'>;
}
declare module 'react-with-styles-interface-aphrodite/test/utils/resolveWithRTL_test.js' {
  declare module.exports: $Exports<'react-with-styles-interface-aphrodite/test/utils/resolveWithRTL_test'>;
}
declare module 'react-with-styles-interface-aphrodite/test/utils/withRTLExtension_test.js' {
  declare module.exports: $Exports<'react-with-styles-interface-aphrodite/test/utils/withRTLExtension_test'>;
}
declare module 'react-with-styles-interface-aphrodite/test/with-rtl_test.js' {
  declare module.exports: $Exports<'react-with-styles-interface-aphrodite/test/with-rtl_test'>;
}
declare module 'react-with-styles-interface-aphrodite/with-rtl.js' {
  declare module.exports: $Exports<'react-with-styles-interface-aphrodite/with-rtl'>;
}
