// flow-typed signature: 51ff7a28866158e4e5eaf08c8bdeb6b9
// flow-typed version: <<STUB>>/@okta/okta-react_v^3.0.7/flow_v0.135.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@okta/okta-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@okta/okta-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@okta/okta-react/dist/AuthService' {
  declare module.exports: any;
}

declare module '@okta/okta-react/dist' {
  declare module.exports: any;
}

declare module '@okta/okta-react/dist/LoginCallback' {
  declare module.exports: any;
}

declare module '@okta/okta-react/dist/OktaContext' {
  declare module.exports: any;
}

declare module '@okta/okta-react/dist/OktaError' {
  declare module.exports: any;
}

declare module '@okta/okta-react/dist/packageInfo' {
  declare module.exports: any;
}

declare module '@okta/okta-react/dist/SecureRoute' {
  declare module.exports: any;
}

declare module '@okta/okta-react/dist/Security' {
  declare module.exports: any;
}

declare module '@okta/okta-react/dist/withOktaAuth' {
  declare module.exports: any;
}

declare module '@okta/okta-react/src/AuthService' {
  declare module.exports: any;
}

declare module '@okta/okta-react/src' {
  declare module.exports: any;
}

declare module '@okta/okta-react/src/LoginCallback' {
  declare module.exports: any;
}

declare module '@okta/okta-react/src/OktaContext' {
  declare module.exports: any;
}

declare module '@okta/okta-react/src/OktaError' {
  declare module.exports: any;
}

declare module '@okta/okta-react/src/packageInfo' {
  declare module.exports: any;
}

declare module '@okta/okta-react/src/SecureRoute' {
  declare module.exports: any;
}

declare module '@okta/okta-react/src/Security' {
  declare module.exports: any;
}

declare module '@okta/okta-react/src/withOktaAuth' {
  declare module.exports: any;
}

// Filename aliases
declare module '@okta/okta-react/dist/AuthService.js' {
  declare module.exports: $Exports<'@okta/okta-react/dist/AuthService'>;
}
declare module '@okta/okta-react/dist/index' {
  declare module.exports: $Exports<'@okta/okta-react/dist'>;
}
declare module '@okta/okta-react/dist/index.js' {
  declare module.exports: $Exports<'@okta/okta-react/dist'>;
}
declare module '@okta/okta-react/dist/LoginCallback.js' {
  declare module.exports: $Exports<'@okta/okta-react/dist/LoginCallback'>;
}
declare module '@okta/okta-react/dist/OktaContext.js' {
  declare module.exports: $Exports<'@okta/okta-react/dist/OktaContext'>;
}
declare module '@okta/okta-react/dist/OktaError.js' {
  declare module.exports: $Exports<'@okta/okta-react/dist/OktaError'>;
}
declare module '@okta/okta-react/dist/packageInfo.js' {
  declare module.exports: $Exports<'@okta/okta-react/dist/packageInfo'>;
}
declare module '@okta/okta-react/dist/SecureRoute.js' {
  declare module.exports: $Exports<'@okta/okta-react/dist/SecureRoute'>;
}
declare module '@okta/okta-react/dist/Security.js' {
  declare module.exports: $Exports<'@okta/okta-react/dist/Security'>;
}
declare module '@okta/okta-react/dist/withOktaAuth.js' {
  declare module.exports: $Exports<'@okta/okta-react/dist/withOktaAuth'>;
}
declare module '@okta/okta-react/src/AuthService.js' {
  declare module.exports: $Exports<'@okta/okta-react/src/AuthService'>;
}
declare module '@okta/okta-react/src/index' {
  declare module.exports: $Exports<'@okta/okta-react/src'>;
}
declare module '@okta/okta-react/src/index.js' {
  declare module.exports: $Exports<'@okta/okta-react/src'>;
}
declare module '@okta/okta-react/src/LoginCallback.js' {
  declare module.exports: $Exports<'@okta/okta-react/src/LoginCallback'>;
}
declare module '@okta/okta-react/src/OktaContext.js' {
  declare module.exports: $Exports<'@okta/okta-react/src/OktaContext'>;
}
declare module '@okta/okta-react/src/OktaError.js' {
  declare module.exports: $Exports<'@okta/okta-react/src/OktaError'>;
}
declare module '@okta/okta-react/src/packageInfo.js' {
  declare module.exports: $Exports<'@okta/okta-react/src/packageInfo'>;
}
declare module '@okta/okta-react/src/SecureRoute.js' {
  declare module.exports: $Exports<'@okta/okta-react/src/SecureRoute'>;
}
declare module '@okta/okta-react/src/Security.js' {
  declare module.exports: $Exports<'@okta/okta-react/src/Security'>;
}
declare module '@okta/okta-react/src/withOktaAuth.js' {
  declare module.exports: $Exports<'@okta/okta-react/src/withOktaAuth'>;
}
